import type { Metadata } from "next";
import { Roboto_Mono, Roboto } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/shared/providers/auth-provider";
import { QueryProvider } from "./query-provider";
import { Toast } from "@heroui/react";

const robotoSans = Roboto({
	variable: "--font-roboto-sans",
	subsets: ["latin"],
});

const robotoMono = Roboto_Mono({
	variable: "--font-roboto-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className={`${robotoSans.variable} ${robotoMono.variable} dark h-full antialiased`} data-theme="dark">
			<body className="flex min-h-full flex-col">
				<Toast.Provider placement="top" />
				<QueryProvider>
					<AuthProvider>{children}</AuthProvider>
				</QueryProvider>
			</body>
		</html>
	);
}
